<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/151004/1-1510041K542.jpg ",93,238);
$z[1][4]['ddimg']="/uploads/allimg/151004/1-1510041K542.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="739";
$z[1][4]['height']="581";
$z[2]=Array("img"," /uploads/allimg/151004/1-1510041K544.jpg ",240,385);
$z[2][4]['ddimg']="/uploads/allimg/151004/1-1510041K544.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="738";
$z[2][4]['height']="596";
$z[3]=Array("img"," /uploads/allimg/151004/1-1510041K547.jpg ",387,532);
$z[3][4]['ddimg']="/uploads/allimg/151004/1-1510041K547.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="761";
$z[3][4]['height']="557";
$z[4]=Array("img"," /uploads/allimg/151004/1-1510041K550.jpg ",534,679);
$z[4][4]['ddimg']="/uploads/allimg/151004/1-1510041K550.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="730";
$z[4][4]['height']="485";

?>