{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/151005/1-151005200T4.jpg' text='' width='800' height='600'} /uploads/allimg/151005/1-151005200T4.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/151005/1-151005200T7.jpg' text='' width='1024' height='682'} /uploads/allimg/151005/1-151005200T7.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/151005/1-151005200T9.jpg' text='' width='1280' height='960'} /uploads/allimg/151005/1-151005200T9.jpg {/dede:img}
