<?php
$z[0]=Array("field","",202,221);
$z[0][4]['name']="title";
$z[1]=Array("global","",222,248);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1284,1319);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",1563,1592);
$z[3][4]['name']="typename";
$z[4]=Array("field","",1621,1650);
$z[4][4]['name']="position";
$z[5]=Array("productimagelist","\r\n			  <li><a class=\"example-image-link\" href=\"[field:imgsrc/]\" data-lightbox=\"example-set\" target=\"_blank\"><img class=\"example-image\" src=\"[field:imgsrc/]\" alt=\"[field:text/]\"/></a></li>\r\n			  ",1842,2083);
$z[6]=Array("productimagelist","\r\n			<a data-slide-index=\"0\" href=\"[field:imgsrc/]\"><img src=\"[field:imgsrc/]\" /></a>\r\n			",2140,2277);
$z[7]=Array("field","",2357,2376);
$z[7][4]['name']="title";
$z[8]=Array("prenext","",2490,2515);
$z[8][4]['get']="pre";
$z[9]=Array("prenext","",2572,2598);
$z[9][4]['get']="next";
$z[10]=Array("arclist","\r\n		  <div class=\"col-sm-6 col-md-3 col-mm-6 pro_pic_bg\">\r\n            <div class=\"thumbnail pro_pic\"><a href=\"[field:arcurl/]\"><img  class=\"img-thumbnail\" src=\"[field:picname/]\" alt=\"[field:title/]\"/></a>\r\n              <h3><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></h3>\r\n            </div>\r\n          </div>\r\n		  ",2732,3148);
$z[10][4]['typeid']="2";
$z[10][4]['row']="4";
$z[10][4]['titlelen']="20";
$z[10][4]['orderby']="pubdate";
$z[11]=Array("include","",3233,3269);
$z[11][4]['filename']="left1.htm";
$z[12]=Array("include","",3301,3338);
$z[12][4]['filename']="footer.htm";

?>