<?php
$z[0]=Array("field","",202,221);
$z[0][4]['name']="title";
$z[1]=Array("global","",222,248);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1286,1321);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",1606,1635);
$z[3][4]['name']="position";
$z[4]=Array("productimagelist","\r\n			  <li><a class=\"example-image-link\" href=\"[field:imgsrc/]\" data-lightbox=\"example-set\" target=\"_blank\"><img class=\"example-image\" src=\"[field:imgsrc/]\" alt=\"[field:text/]\"/></a></li>\r\n			  ",1820,2061);
$z[5]=Array("productimagelist","\r\n			<a data-slide-index=\"0\" href=\"[field:imgsrc/]\"><img src=\"[field:imgsrc/]\" /></a>\r\n			",2118,2255);
$z[6]=Array("field","",2398,2417);
$z[6][4]['name']="title";
$z[7]=Array("field","",2496,2517);
$z[7][4]['name']="bianhao";
$z[8]=Array("field","",2557,2577);
$z[8][4]['name']="jiaodu";
$z[9]=Array("field","",2617,2638);
$z[9][4]['name']="xiangsu";
$z[10]=Array("field","</li>\r\n              <li>\r\n                  <a href=\"http://wpa.qq.com/msgrd?v=3&uin=123456789&site=qq&menu=yes\" class=\"btn btn-danger\">在线订购</a>\r\n              </li>\r\n            </ul>\r\n          </div>\r\n        </div>\r\n        <div class=\"product_con\">\r\n          {dede:field.body",2737,3053);
$z[10][4]['name']="description";
$z[11]=Array("prenext","",3177,3202);
$z[11][4]['get']="pre";
$z[12]=Array("prenext","",3259,3285);
$z[12][4]['get']="next";
$z[13]=Array("arclist","\r\n		  <div class=\"col-sm-6 col-md-3 col-mm-6 pro_pic_bg\">\r\n            <div class=\"thumbnail pro_pic\"><a href=\"[field:arcurl/]\"><img  class=\"img-thumbnail\" src=\"[field:picname/]\" alt=\"[field:title/]\"/></a>\r\n              <h3><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></h3>\r\n            </div>\r\n          </div>\r\n		  ",3425,3841);
$z[13][4]['typeid']="2";
$z[13][4]['row']="4";
$z[13][4]['titlelen']="20";
$z[13][4]['orderby']="pubdate";
$z[14]=Array("include","",3943,3978);
$z[14][4]['filename']="left.htm";
$z[15]=Array("include","",4010,4047);
$z[15][4]['filename']="footer.htm";

?>