<?php
$z[0]=Array("channelartlist"," \r\n		  <li class=\"dropdown\"><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename' /}</a>\r\n		  <a href=\"{dede:field name='typeurl'/}\" id=\"app_menudown\" style=\"\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\"><span class=\"glyphicon glyphicon-menu-down btn-xs\"></span></a>\r\n            <ul class=\"dropdown-menu nav_small\" role=\"menu\">\r\n              {dede:channel type='son' noself='yes'}\r\n			  <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n              {/dede:channel} \r\n            </ul>\r\n          </li>\r\n		  ",692,1329);
$z[0][4]['typeid']="top";
$z[0][4]['row']="8";

?>