<?php
$z[0]=Array("global","",205,231);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("include","",891,926);
$z[1][4]['filename']="head.htm";
$z[2]=Array("arclist","\r\n			<li><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a><span class='news_time'>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span></li>\r\n			",2535,2774);
$z[2][4]['typeid']="7";
$z[2][4]['row']="6";
$z[2][4]['titlelen']="80";
$z[2][4]['orderby']="pubdate";
$z[3]=Array("arclist","\r\n	  <div class=\"slide\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img name=\"opacity_img\" src=\"[field:picname/]\" alt=\"[field:title/]\"/></a>\r\n        <h3 class=\"product_h3\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></h3>\r\n      </div>\r\n	  ",3400,3746);
$z[3][4]['typeid']="2";
$z[3][4]['row']="12";
$z[3][4]['titlelen']="30";
$z[3][4]['orderby']="pubdate";
$z[4]=Array("arclist","\r\n		  <div class=\"col-sm-6 col-md-4 col-mm-4 cases_pic_bg\">\r\n            <div class=\"thumbnail cases_pic\"><a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" class=\"img-thumbnail\" /></a>\r\n              <h3><a href=\"[field:arcurl/]\">[field:title/]</a></h3>\r\n            </div>\r\n          </div>\r\n		  ",4536,4913);
$z[4][4]['typeid']="11";
$z[4][4]['row']="3";
$z[4][4]['titlelen']="20";
$z[4][4]['orderby']="pubdate";
$z[5]=Array("include","",6074,6111);
$z[5][4]['filename']="footer.htm";

?>