<?php
$z[0]=Array("channel","\r\n            <li><a class='curret' href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n            ",224,469);
$z[0][4]['row']="10";
$z[0][4]['typeid']="2";
$z[0][4]['type']="son";
$z[0][4]['col']="1";
$z[0][4]['currentstyle']="<li><a class='cur' href='~typelink~' ~rel~>~typename~</a></li>";
$z[1]=Array("arclist","\r\n            <li><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a><span class='news_time'>[field:pubdate\r\n                function=\"MyDate('Y-m-d',@me)\"/]</span></li>\r\n            ",690,964);
$z[1][4]['typeid']="7";
$z[1][4]['row']="6";
$z[1][4]['titlelen']="40";
$z[1][4]['orderby']="pubdate";
$z[2]=Array("global","",1064,1089);
$z[2][4]['name']="cfg_rexian";

?>