<?php
$z[0]=Array("field","",202,221);
$z[0][4]['name']="title";
$z[1]=Array("global","",222,248);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",914,949);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",1234,1263);
$z[3][4]['name']="position";
$z[4]=Array("field","",1325,1346);
$z[4][4]['name']="content";
$z[5]=Array("include","",1720,1756);
$z[5][4]['filename']="left1.htm";
$z[6]=Array("include","",1788,1825);
$z[6][4]['filename']="footer.htm";

?>