<?php
$z[0]=Array("field","",202,221);
$z[0][4]['name']="title";
$z[1]=Array("global","",222,248);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",914,949);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",1234,1263);
$z[3][4]['name']="position";
$z[4]=Array("list","\r\n			<li><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a><span class=\"news_time\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span></li>\r\n			",1330,1545);
$z[4][4]['pagesize']="15";
$z[4][4]['titlelen']="80";
$z[5]=Array("pagelist","",1597,1660);
$z[5][4]['listitem']="index,info,next,pageno";
$z[5][4]['listsize']="5";
$z[6]=Array("include","",1750,1785);
$z[6][4]['filename']="left.htm";
$z[7]=Array("include","",1817,1854);
$z[7][4]['filename']="footer.htm";

?>