<?php
$z[0]=Array("field","",202,221);
$z[0][4]['name']="title";
$z[1]=Array("global","",222,248);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",915,950);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",1194,1223);
$z[3][4]['name']="typename";
$z[4]=Array("field","",1252,1281);
$z[4][4]['name']="position";
$z[5]=Array("list","\r\n		  <div class=\"col-sm-6 col-md-3 col-mm-6 pro_pic_bg\">\r\n            <div class=\"thumbnail pro_pic\"><a href=\"[field:arcurl/]\"><img  src=\"[field:picname/]\" alt=\"[field:title/]\" class=\"img-thumbnail\"/></a>\r\n              <h3><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></h3>\r\n            </div>\r\n          </div>\r\n		  ",1313,1705);
$z[5][4]['pagesize']="15";
$z[5][4]['titlelen']="80";
$z[6]=Array("pagelist","",1735,1794);
$z[6][4]['listitem']="index,pre,next,end";
$z[6][4]['listsize']="5";
$z[7]=Array("include","",1884,1920);
$z[7][4]['filename']="left1.htm";
$z[8]=Array("include","",1952,1989);
$z[8][4]['filename']="footer.htm";

?>