<?php
$z[0]=Array("field","",202,221);
$z[0][4]['name']="title";
$z[1]=Array("global","",222,248);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",914,949);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",1234,1263);
$z[3][4]['name']="position";
$z[4]=Array("list","\r\n		  <div class=\"col-sm-6 col-md-3 col-mm-6 pro_pic_bg\">\r\n            <div class=\"thumbnail pro_pic\"><a href=\"[field:arcurl/]\"><img  src=\"[field:picname/]\" alt=\"[field:title/]\" class=\"img-thumbnail\"/></a>\r\n              <h3><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></h3>\r\n            </div>\r\n          </div>\r\n		  ",1296,1673);
$z[4][4]['pagesize']="8";
$z[5]=Array("pagelist","",1703,1762);
$z[5][4]['istitem']="index,pre,next,end,";
$z[5][4]['listsize']="5";
$z[6]=Array("include","",1852,1887);
$z[6][4]['filename']="left.htm";
$z[7]=Array("include","",1919,1956);
$z[7][4]['filename']="footer.htm";

?>